### ISSUE TITLE
Unable to set property value which is required on a stubbed object

### ISSUE THREAD

**Issue by cookie-bytes** [guzzlerio/deride#57]

**Comment by REAANDREW** [comment]
Could you paste a failing test into the issue?

**Comment by cookie-bytes** [comment]
Hi, I have created a fork and going to send pull request when added it.


Sent by Outlook for Android





On Wed, Jul 15, 2015 at 5:54 AM -0700, "Andrew Rea" <notifications@github.com> wrote:
Could you paste a failing test into the issue?

---
