### ISSUE TITLE
Unexpected difference in behaviour between 1.1.0 and 1.2.0

### ISSUE THREAD

**Issue by Stono** [guzzlerio/deride#80]
Long time no speak folks.

I'm still using this library quite extensively and also have a few other teams at ThoughtWorks on it too.  After upgrading one of my projects to `1.2.0` this morning I had some failing tests, upon investigation it appears that I can no longer override the behaviour of a given expect.

Take the following example:

```
'use strict';
const deride = require('deride');
const thing = deride.wrap({ example: () => {} });

thing.setup.example.toCallbackWith([null, 1]);
thing.setup.example.toCallbackWith([null, 2]);

thing.example((err, number) => {
  console.log(number);
});
```

On `1.1.x`, the result is `2`, on `1.2.0` the result is `1`.  

This causes us some issues because we have a whole bunch of tests that have an initial `thing.setup.example`, and then further down the line change the behaviour of `thing.setup.example` to do something else.  An example is we have a generic stub API which we use across multiple tests, and in some of them we want to override the default behaviour that's configured as part of the stub to do something slightly different.

**Comment by jamlen** [comment]
Hey up Karlos! Hmmm wasn't expecting that! I'll make a testcase for it and get straight on it, unless you are already looking at it?

**Comment by jamlen** [comment]
OK I'll take a quick look now and if its a quick fix I'll sort it, otherwise it might take a few days/week or so.

Also BTW you drop the array brackets in the setup, makes it more readable:

```js
thing.setup.example.toCallbackWith(null, 1);
```

**Comment by jamlen** [comment]
Booom! Failing test 😄 now to see whats going south!

**Comment by Stono** [comment]
Yup that's a perfect representation of the issue

**Comment by jamlen** [comment]
Only took me 5 years @Stono! but its now fixed in v.1.3.0
